-- MySQL Script generated by MySQL Workbench
-- Mon Aug 19 10:55:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Monitorando
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Monitorando
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Monitorando` DEFAULT CHARACTER SET utf8 ;
USE `Monitorando` ;

-- -----------------------------------------------------
-- Table `Monitorando`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(65) NOT NULL,
  `Senha` VARCHAR(100) NOT NULL,
  `Tipo` ENUM('Aluno', 'Professor') NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Foto` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Fellipe Costa Reis", "0000004", "Aluno", "fcr@gmail.com", "imagem1.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Fernanda Cesar da Silva", "0000003", "Aluno", "g.reis@gmail.com", "imagem2.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Kayane Rocha ", "0000002", "Aluno", "ghuyiyg@gmail.com", "imagem3.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Natália Penalva Panighel", "0000001", "Aluno", "fellipe@gmail.com", "imagem4.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Angelecia Ferreira Gomes", "0000005", "Aluno", "angel.ferreira@gmail.com", "imagem5.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Jean Vitor Hass", "0000006", "Aluno", "jean.hass@gmail.com", "imagem6.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Bruno Ferreira Ribeiro", "0000007", "Aluno", "bruno.ddff@gmail.com", "imagem7.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Cristina Soares", "0000008", "Aluno", "cris.almeida@gmail.com", "imagem8.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Ana Beatriz Nascimento", "0000009", "Aluno", "bia.luscas@gmail.com", "imagem9.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Camilla Cabello ", "0000010", "Aluno", "a.leao@gmail.com", "imagem10.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Shawn Petter Raul Mendes", "0000011", "Aluno", "cans.c@gmail.com", "imagem11.png/AAAAA");
INSERT INTO `Monitorando`.`Usuario` (`Nome`, `Senha`, `Tipo`, `Email`, `Foto`) VALUES ("Shawnmilla não é fake", "00000", "Aluno", "melhorcasal@gmail.com", "imagem12.png/AAAAA");







-- -----------------------------------------------------
-- Table `Monitorando`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Curso` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

INSERT INTO `Monitorando`.`Curso` (`Nome`) VALUES ("Informática");
INSERT INTO `Monitorando`.`Curso` (`Nome`) VALUES ("Mecanica");
INSERT INTO `Monitorando`.`Curso` (`Nome`) VALUES ("Eletronica");
INSERT INTO `Monitorando`.`Curso` (`Nome`) VALUES ("Eletrotecnica");
INSERT INTO `Monitorando`.`Curso` (`Nome`) VALUES ("Informática Integrado");
INSERT INTO `Monitorando`.`Curso` (`Nome`) VALUES ("Mecanica Integrado");
INSERT INTO `Monitorando`.`Curso` (`Nome`) VALUES ("Eletronica Integrado");
INSERT INTO `Monitorando`.`Curso` (`Nome`) VALUES ("Eletrotecnica Integrado");


-- -----------------------------------------------------
-- Table `Monitorando`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Turma` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NOT NULL,
  `Curso_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Turma_Curso1_idx` (`Curso_Id` ASC),
  CONSTRAINT `fk_Turma_Curso1`
    FOREIGN KEY (`Curso_Id`)
    REFERENCES `Monitorando`.`Curso` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `Monitorando`.`Turma` (`Numero`, `Curso_Id`) VALUES (113, 1);


-- -----------------------------------------------------
-- Table `Monitorando`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Aluno` (
  `Id` INT NOT NULL,
  `Status` ENUM('Monitor', 'Comum') NOT NULL,
  `IdUsuario` INT NOT NULL,
  `Id Turma` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Aluno_Usuario1_idx` (`IdUsuario` ASC),
  INDEX `fk_Aluno_Turma1_idx` (`Id Turma` ASC),
  CONSTRAINT `fk_Aluno_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `Monitorando`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Turma1`
    FOREIGN KEY (`Id Turma`)
    REFERENCES `Monitorando`.`Turma` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitorando`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Professor` (
  `Id` INT NOT NULL,
  `Disciplina` VARCHAR(60) NOT NULL,
  `IdUsuario` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Professor_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_Professor_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `Monitorando`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitorando`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Local` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Identificacao` VARCHAR(15) NOT NULL,
  `Tipo` ENUM('Laboratório', 'Sala') NOT NULL,
  `Bloco` ENUM('Bloco A', 'Bloco C', 'Bloco D', 'Bloco E', 'Bloco F') NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (300, "Sala", "Bloco A");
INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (301, "Sala", "Bloco A");
INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (302, "Sala", "Bloco A");
INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (303, "Sala", "Bloco A");
INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (304, "Sala", "Bloco A");
INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (305, "Sala", "Bloco A");
INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (306, "Sala", "Bloco A");
INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (307, "Sala", "Bloco A");
INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (308, "Sala", "Bloco A");
INSERT INTO `Monitorando`.`Local` (`Identificacao`, `Tipo`, `Bloco`) VALUES (309, "Sala", "Bloco A");


-- -----------------------------------------------------
-- Table `Monitorando`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Disciplina` (
  `Id` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Curso` VARCHAR(45) NOT NULL,
  `Curso_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Disciplina_Curso1_idx` (`Curso_Id` ASC),
  CONSTRAINT `fk_Disciplina_Curso1`
    FOREIGN KEY (`Curso_Id`)
    REFERENCES `Monitorando`.`Curso` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitorando`.`Codigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Codigo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A02");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A03");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A04");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A05");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A06");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A07");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A08");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A09");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A10");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A11");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A12");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A13");
INSERT INTO `Monitorando`.`Codigo` (`Codigo`) VALUES ("A14");




-- -----------------------------------------------------
-- Table `Monitorando`.`Monitor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Monitor` (
  `Id` INT NOT NULL,
  `Código` VARCHAR(45) NOT NULL,
  `Id Usuario` INT NOT NULL,
  `Status` ENUM('Ativo', 'Desativado', 'Verificando') NOT NULL,
  `Codigo_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Monitor_Usuario1_idx` (`Id Usuario` ASC),
  INDEX `fk_Monitor_Codigo1_idx` (`Codigo_Id` ASC),
  CONSTRAINT `fk_Monitor_Usuario1`
    FOREIGN KEY (`Id Usuario`)
    REFERENCES `Monitorando`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Monitor_Codigo1`
    FOREIGN KEY (`Codigo_Id`)
    REFERENCES `Monitorando`.`Codigo` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitorando`.`Monitoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Monitoria` (
  `Id` INT NOT NULL,
  `Conteudo` VARCHAR(100) NOT NULL,
  `DataHorario` DATETIME NOT NULL,
  `NumVagas` INT NOT NULL,
  `NumInscritos` INT NOT NULL,
  `Descricao` MEDIUMTEXT NOT NULL,
  `IdLocal` INT NOT NULL,
  `IdDisciplina` INT NOT NULL,
  `Id Monitor` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Monitoria_Local1_idx` (`IdLocal` ASC),
  INDEX `fk_Monitoria_Disciplina1_idx` (`IdDisciplina` ASC),
  INDEX `fk_Monitoria_Monitor1_idx` (`Id Monitor` ASC),
  CONSTRAINT `fk_Monitoria_Local1`
    FOREIGN KEY (`IdLocal`)
    REFERENCES `Monitorando`.`Local` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Monitoria_Disciplina1`
    FOREIGN KEY (`IdDisciplina`)
    REFERENCES `Monitorando`.`Disciplina` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Monitoria_Monitor1`
    FOREIGN KEY (`Id Monitor`)
    REFERENCES `Monitorando`.`Monitor` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitorando`.`Inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Inscricao` (
  `Id` INT NOT NULL,
  `IdUsuario` INT NOT NULL,
  `IdMonitoria` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Inscricao_Usuario1_idx` (`IdUsuario` ASC),
  INDEX `fk_Inscricao_Monitoria1_idx` (`IdMonitoria` ASC),
  CONSTRAINT `fk_Inscricao_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `Monitorando`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscricao_Monitoria1`
    FOREIGN KEY (`IdMonitoria`)
    REFERENCES `Monitorando`.`Monitoria` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitorando`.`Avalicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Avalicao` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Conteudo` VARCHAR(500) NOT NULL,
  `DataPubli` DATE NOT NULL,
  `Nota` INT NULL,
  `Inscricao_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Avalicao_Inscricao1_idx` (`Inscricao_Id` ASC),
  CONSTRAINT `fk_Avalicao_Inscricao1`
    FOREIGN KEY (`Inscricao_Id`)
    REFERENCES `Monitorando`.`Inscricao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitorando`.`Arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Arquivo` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `IdMonitoria` INT NOT NULL,
  `Local` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Arquivo_Monitoria1_idx` (`IdMonitoria` ASC),
  CONSTRAINT `fk_Arquivo_Monitoria1`
    FOREIGN KEY (`IdMonitoria`)
    REFERENCES `Monitorando`.`Monitoria` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitorando`.`Mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Mensagem` (
  `Id` INT NOT NULL,
  `DataHorario` DATETIME NOT NULL,
  `Conteudo` VARCHAR(500) NOT NULL,
  `Inscricao_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Mensagem_Inscricao1_idx` (`Inscricao_Id` ASC),
  CONSTRAINT `fk_Mensagem_Inscricao1`
    FOREIGN KEY (`Inscricao_Id`)
    REFERENCES `Monitorando`.`Inscricao` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitorando`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monitorando`.`Pedido` (
  `Id` INT NOT NULL,
  `Motivo` TEXT NOT NULL,
  `Data` DATETIME NOT NULL,
  `Aluno_Id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Pedido_Aluno1_idx` (`Aluno_Id` ASC),
  CONSTRAINT `fk_Pedido_Aluno1`
    FOREIGN KEY (`Aluno_Id`)
    REFERENCES `Monitorando`.`Aluno` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




